import { Inter } from "next/font/google";
import "./globals.css";
import { Font } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Barlow, Roboto, Poppins } from "next/font/google";
import Header from "./components/ui/Header";
import Footer from "./components/ui/Footer";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
